name: sprout_tests_UI

# Определение события, запускающего workflow
on: 
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  schedule:
    # - cron: '0 5 * * *'    
    - cron: '0 14 * * *'

# Определение Задачи(job)
jobs:
  # Основная часть тестов
  tests:
    timeout-minutes: 60

    # Уникальный ключ для группы задач предназначен для того, чтобы повторный запуск Джобы вставал в ожидание, не конфликтуая с первым
    concurrency: sprout_tests_UI_concurrency

    # запуск на виртуальной машине
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && (github.event.schedule == '0 5 * * *' || github.event.schedule == '0 14 * * *'))
    runs-on: ubuntu-latest
    env:
      ADMIN_BUYER_EMAIL: ${{ secrets.ADMIN_BUYER_EMAIL }}
      ADMIN_BUYER_PASSWORD: ${{ secrets.ADMIN_BUYER_PASSWORD }}
      TEST_BUYER_EMAIL: ${{ secrets.TEST_BUYER_EMAIL }}
      TEST_BUYER_PASSWORD: ${{ secrets.TEST_BUYER_PASSWORD }}
      ADMIN_SELLER_EMAIL: ${{ secrets.ADMIN_SELLER_EMAIL }}
      ADMIN_SELLER_PASSWORD: ${{ secrets.ADMIN_SELLER_PASSWORD }}
      PURCHASER_EMAIL: ${{ secrets.PURCHASER_EMAIL }}
      PURCHASER_PASSWORD: ${{ secrets.PURCHASER_PASSWORD }}
      CONTRACT_MANAGER_EMAIL: ${{ secrets.CONTRACT_MANAGER_EMAIL }}
      CONTRACT_MANAGER_PASSWORD: ${{ secrets.CONTRACT_MANAGER_PASSWORD }}
      TESTMAIL_ADRESS_: ${{ secrets.TESTMAIL_ADRESS_ }}
      TESTMAIL_JSON_: ${{ secrets.TESTMAIL_JSON_ }}

    steps:

      # Клонирование репозитория
      - uses: actions/checkout@v4

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Показать cwd и содержимое директории проекта
        run: |
          pwd
          ls -l
          ls -l auth_states || echo "auth_states пока нет"

      # Установка браузеров
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      # Запуск тестов
      - name: Run tests
        run: |
          pytest --alluredir=allure-results --tb=short -v

      - name: Показать содержимое auth_states после тестов
        if: always()
        run: |
          echo "::group::Содержимое папки auth_states"
          ls -l auth_states || echo "Папка auth_states не создана"
          find . -type f -name '*.json'
          echo "::endgroup::"

      - name: Показать размеры storage_state файлов
        if: always()
        run: |
          echo "::group::Размеры файлов auth_states"
          if [ -d auth_states ]; then
            for f in auth_states/*.json; do
              echo "$(stat -c '%12s %n' "$f")"
            done
          else
            echo "Папки auth_states нет"
          fi
          echo "::endgroup::"

      - name: Показать первые строки каждого storage_state
        if: always()
        run: |
          echo "::group::Первые строки storage_state файлов"
          if [ -d auth_states ]; then
            for f in auth_states/*.json; do
              echo "==== $f ===="
              head -20 "$f"
              echo ""
            done
          else
            echo "Папки auth_states нет"
          fi
          echo "::endgroup::"
          
      # Проверка наличия json-файлов в allure-results (чтобы не запушить сломаный отчет)
      - name: Check if Allure results exist
        if: always()
        id: check_allure
        run: |
          if [ -d allure-results ] && [ "$(ls -A allure-results/*.json 2>/dev/null)" ]; then
            echo "allure_results_exist=true" >> $GITHUB_OUTPUT
          else
            echo "allure_results_exist=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Debug allure_results_exist
        if: always()
        run: echo "allure_results_exist=${{ steps.check_allure.outputs.allure_results_exist }}"

      # Загрузка артефактов
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always() && steps.check_allure.outputs.allure_results_exist == 'true'
        with:
          name: allure-results-main-${{ github.run_id }}
          path: allure-results/
          # retention_days: 10

      # Получение истории прогонов Allure
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always() && steps.check_allure.outputs.allure_results_exist == 'true'
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Генерация отчета с учетом истории прогонов
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always() && steps.check_allure.outputs.allure_results_exist == 'true'
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # Публикация отчета Allure  
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v2
        if: always() && steps.check_allure.outputs.allure_results_exist == 'true'
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  notify-on-failure:
    if: |
      failure() ||
      (needs.test && needs.tests.result != 'success' && needs.tests.result != 'skipped')
    runs-on: ubuntu-latest
    # needs: test
    needs: [tests]
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "❌ GitHub Actions FAILED in ${{ github.repository }}"
          body: |
           ❗ Workflow [${{ github.workflow }}] failed.

            🔗 View it here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            📦 Commit: ${{ github.sha }}
            👤 Triggered by: ${{ github.actor }}
          to: urin.a@garagetools.ru, timofeev.a@garagetools.ru
          from: GitHub Actions <${{ secrets.GMAIL_USERNAME }}>
